//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string MaNhanVien { get; set; }
        public string HoVaTen { get; set; }
        public bool GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string TrinhDo { get; set; }
        public string NoiDaoTao { get; set; }
        public string ChuyenNganh { get; set; }
        public string ViTri { get; set; }
        public string DonVi { get; set; }
        public Nullable<System.DateTime> NgayThuViec { get; set; }
        public Nullable<System.DateTime> NgayChinhThuc { get; set; }
        public string LoaiHopDong { get; set; }
        public bool TrangThai { get; set; }
    }
}
