//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_TEST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Key]
        public int MaNhanVien { get; set; }
        public string HoVaTen { get; set; }
        public string GioiTinh { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime NgaySinh { get; set; }
        public string TrinhDoDaoTao { get; set; }
        public string NoiDaoTao { get; set; }
        public string ChuyenNganh { get; set; }
        public string ViTriCongViec { get; set; }
        public string DonViCongTac { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayThuViec { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayChinhThuc { get; set; }
        public string LoaiHopDong { get; set; }
        public string TrangThai { get; set; }
    }
}
